### PR TITLE
minor Makefile cleanup and introduced gcc warnings

### PR DESCRIPTION
**Pull request by mrundle**
Pretty cool! Forked the repo to try it out and couldn't resist tweaking the Makefile a little bit. 

An outline of changes:

- Made ncurses an official dependency so that people don't have to worry about missing it in the Readme. The "-y" flag could be used to automatically download and make the build promptless (without it, apt-get will prompt for a yes/no), but it seems like a good idea to give the user a heads up before committing to library install. 

- Made the "obj" and "bin" directories order-only-prerequisites for their respective files, and defined rules for creating them. That way you don't need to have two separate .gitignores to hold up the empty directories. Being able to just have a src directory, Makefile, and ancillary documentation seems a lot cleaner.

- Introduced gcc warnings and removed a couple of unused variables that they caught. -Werror might be a good one too when you're developing (it treats all warnings as errors.)

### CODE REVIEW

**Comment by bartobri** [comment]
Hi! Thanks for the interest in my project!

Couple questions about your pull request:

1) Now that you changed the makefile to dynamically create obj/ and bin/ when needed, do they show up in 'git status'? If so, that would be a little annoying and I'd probably prefer to keep it as is.

2) I see you added Ubuntu apt-get commands to the makefile for ncurses. But what happens if someone builds on a different flavor of linux?

Thanks,
Brian

**Comment by mrundle** [comment]
1) Nope, as everything in obj/ and bin/ are included in the top level .gitignore, they don't show up in git status (git doesn't track empty directories.) Had to double check to make sure of that.

2) Good point - as it was, the apt-get command would have failed on those distros and they would have had to configure manually. I added a 'configure' script that the Makefile can call (or that the user can run standalone) that tries to determine the package manager before installing ncurses. I based the package manager determination logic off of http://unix.stackexchange.com/questions/46081/identifying-the-system-package-manager. The nice thing about this addition is that it's basically a helpful bonus; it doesn't break anything that would have otherwise worked in the worst case, and in the best case makes building a lot easier.

**Comment by mrundle** [comment]
I think I actually prefer this: https://github.com/bartobri/no-more-secrets/pull/10

**Comment by bartobri** [comment]
Yep. I just merged #10. Closing this one.

**Pull request closed without merging**
