### PR TITLE
Added manpages

### PR DESCRIPTION
**Pull request by susnux**
These are some manpages used for openSUSE.
Maybe you want to merge them into your git repository :-)

### CODE REVIEW

**Comment by jubalh** [comment]
@bartobri if you take these changes in, would you consider creating a new release (0.3.1?) then we could update to that directly and stay with GPL3 and skip the license change for 0.3.0.

**Comment by bartobri** [comment]
@susnux Thanks! Merged!

@jubalh Yes I will update the version shortly.

**Comment by bartobri** [comment]
@jubalh Release 0.3.1 has been created.

**Comment by jubalh** [comment]
@bartobri  thanks! openSUSE build already triggered :)

**Pull request merged**
