### PR TITLE
use freopen(3) correctly

### LINKED ISSUE #74: fails to build with clang 8
I tried to build this program on my phone and got the following error:

```
$ clang --version
clang version 8.0.0 (tags/RELEASE_800/final)
Target: arm-unknown-linux-android
Thread model: posix
InstalledDir: /data/data/com.termux/files/usr/bin
$ make
cc -Wextra -Wall -O2 -o obj/nmstermio.o -c src/nmstermio.c
src/nmstermio.c:299:9: error: expression is not
      assignable
                stdin = freopen("/dev/tty", "r"...
                ~~~~~ ^
1 error generated.
make: *** [Makefile:37: obj/nmstermio.o] Error 1
```

It worked on my laptop:

```
$ gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ make
mkdir obj
cc -Wextra -Wall -O2 -o obj/input.o -c src/input.c
cc -Wextra -Wall -O2 -o obj/error.o -c src/error.c
cc -Wextra -Wall -O2 -o obj/nmscharset.o -c src/nmscharset.c
cc -Wextra -Wall -O2 -o obj/nmstermio.o -c src/nmstermio.c
cc -Wextra -Wall -O2 -o obj/nmseffect.o -c src/nmseffect.c
cc -Wextra -Wall -O2 -o obj/nms.o -c src/nms.c
mkdir bin
cc -Wextra -Wall -O2 -o bin/nms obj/input.o obj/error.o obj/nmscharset.o obj/nmstermio.o obj/nmseffect.o obj/nms.o
```

So, I tried using clang there:

```
$ clang --version
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
$ make CC=clang
mkdir obj
clang -Wextra -Wall -O2 -o obj/input.o -c src/input.c
clang -Wextra -Wall -O2 -o obj/error.o -c src/error.c
clang -Wextra -Wall -O2 -o obj/nmscharset.o -c src/nmscharset.c
clang -Wextra -Wall -O2 -o obj/nmstermio.o -c src/nmstermio.c
clang -Wextra -Wall -O2 -o obj/nmseffect.o -c src/nmseffect.c
clang -Wextra -Wall -O2 -o obj/nms.o -c src/nms.c
mkdir bin
clang -Wextra -Wall -O2 -o bin/nms obj/input.o obj/error.o obj/nmscharset.o obj/nmstermio.o obj/nmseffect.o obj/nms.o
```

So, I think the difference here is the version of clang.

### PR DESCRIPTION
**Pull request by Humm42**
… fixes #74 …

### CODE REVIEW

**Comment by bartobri** [comment]
According to the freopen() man page:

`The  freopen()  function opens the file whose name is the string pointed to by path and associates the stream pointed to by stream with it.`

This suggests the original core is correct. It has also been tested and is working as expected. Why is this change necessary?

**Comment by Humm42** [comment]
`freopen` associates the stream pointed to by the third parameter with the file. It does not create a new stream to be assigned to the `FILE *`. It is unspecified by ISO C whether you can assign to the standard streams, and it is unspecified what happens when you use them after you assigned to them. The original code does not work with musl-libc.

See also:
- https://en.cppreference.com/w/c/io/freopen
- POSIX on the standard streams, aka. <https://pubs.opengroup.org/onlinepubs/9699919799/functions/stdin.html>, aka. stdin(3p)
- the correct man page, aka. POSIX on freopen, aka. <https://pubs.opengroup.org/onlinepubs/9699919799/functions/freopen.html>, aka. freopen(3p)

From freopen(3p):
> RETURN VALUE
> Upon successful completion, freopen() shall return the value of *stream*.  Otherwise, a null pointer shall be returned, and errno shall be set to indicate the error.

`freopen` returns a copy of the pointer you pass in.

**Review by bartobri — APPROVED** [review]
Looks good. Thanks for the fix!

**Comment by bartobri** [comment]
FYI - Compiling with gcc now issues a warning. 

> src/nmstermio.c:299:3: warning: ignoring return value of ‘freopen’, declared with attribute warn_unused_result [-Wunused-result]
>    freopen("/dev/tty", "r", stdin);
>    ^

**Comment by bartobri** [comment]
FYI - I reverted your commit because it is causing the above gcc compile warning. Feel free to resubmit your fix while also addressing this issue.

**Pull request merged**
